language: go

go:
  - 1.1
  - 1.2

install:
  - go get github.com/acsellers/assert
  - go get github.com/acsellers/inflections
  - go get github.com/davecgh/go-spew/spew
  - go get github.com/tebeka/strftime

script:
  - go test github.com/acsellers/multitemplate
  - go test github.com/acsellers/multitemplate/bham
  - go test github.com/acsellers/multitemplate/mustache
  - go test github.com/acsellers/multitemplate/helpers
