language: go

go:
  - 1.1
  - 1.2
  - tip

install:
  - go get github.com/acsellers/assert

script:
  - go test github.com/acsellers/multitemplate
  - go test github.com/acsellers/multitemplate/bham
  - go test github.com/acsellers/multitemplate/mustache
  - go test github.com/acsellers/multitemplate/helpers
